#ifndef STATES_H
#define STATES_H

// Weather definitions
typedef enum {
  WEATHER_ERROR,
  WEATHER_BLUE_SKY,
  WEATHER_NIGHT,
  WEATHER_OVERCAST,
  WEATHER_GOLDEN,
  WEATHER_SNOW,
  WEATHER_LIGHTNING,
  WEATHER_UNKNOWN
} WeatherType;

#endif // STATES_H
